<?php
class MY_Exceptions extends CI_Exceptions {
    function __construct() {
        parent::__construct();
        $this->CI = & get_instance();
        log_message('debug', 'MY_Exceptions Class Initialized');
    }
    function show_404($page = '', $log_error = TRUE) {
        set_status_header('404');
		$url = 'http://' . $_SERVER['SERVER_NAME'];
		echo($this->show_error('<div style="text-align: right; direction: rtl;">&#1608;&#1580;&#1608;&#1583; &#1582;&#1591;&#1575; !</div>', '<div style="text-align: right; direction: rtl;margin-right: 30px;">&#1575;&#1740;&#1606; &#1589;&#1601;&#1581;&#1607; &#1608;&#1580;&#1608;&#1583; &#1606;&#1583;&#1575;&#1585;&#1583; !<br>&#1605;&#1605;&#1705;&#1606; &#1575;&#1587;&#1578; &#1582;&#1591;&#1575;&#1740;&#1740; &#1585;&#1582; &#1583;&#1575;&#1583;&#1607; &#1576;&#1575;&#1588;&#1583; &#1740;&#1575; &#1575;&#1740;&#1606; &#1589;&#1601;&#1581;&#1607; &#1581;&#1584;&#1601; &#1588;&#1583;&#1607; &#1576;&#1575;&#1588;&#1583; . &#1583;&#1585; &#1607;&#1585; &#1589;&#1608;&#1585;&#1578; &#1575;&#1586; &#1588;&#1605;&#1575; &#1593;&#1584;&#1585; &#1605;&#1740;&#1582;&#1608;&#1575;&#1607;&#1740;&#1605;<br><br>&#1605;&#1740; &#1578;&#1608;&#1575;&#1606;&#1740;&#1583; &#1575;&#1586; <a href="' . $url . '">&#1575;&#1740;&#1606; &#1604;&#1740;&#1606;&#1705;</a> &#1576;&#1607; &#1589;&#1601;&#1581;&#1607; &#1575;&#1589;&#1604;&#1740; &#1587;&#1575;&#1740;&#1578; &#1576;&#1575;&#1586;&#1711;&#1585;&#1583;&#1740;&#1583;</a></div>', 'error_404'));
    }
}
?>